Us14
mcharrod/little-esty-shop pull request #84
Opened 2022-02-23 23:15 UTC by markertmer

toggle button for status on admin merchants index.

changes the order after clicking button, may have to fix later.

2022-02-23 23:55 UTC, mcharrod commented on app/controllers/admin/merchants_controller.rb
> +      if merchant_params.count == 1 # as in, only having :status
Hey Mark, good job with the conditionals. I will say, the way this conditional is written, I could see the count being equal to 1 on multiple cases. For instance, updating the merchant's name. Please update this before we merge this into developer.

2022-02-23 23:56 UTC, mcharrod commented on app/views/admin/merchants/index.html.erb
> +  <% statusing = [ "disabled", "disable" ] if merchant.status == "enabled" %>
I like that this button is dynamic! Great job on making it say "enable" or "disable" based on the params.

2022-02-23 23:56 UTC, mcharrod requested changes
Hey Mark, I've added some comments. Please make some updates to your Admin::MerchantsController before we merge this into developer. Thank you!

2022-02-24 04:06 UTC, markertmer commented on app/views/admin/merchants/index.html.erb
> +  <% statusing = [ "disabled", "disable" ] if merchant.status == "enabled" %>
Thanks Katy!

2022-02-24 04:06 UTC, markertmer commented on app/controllers/admin/merchants_controller.rb
> +      if merchant_params.count == 1 # as in, only having :status
Yeah, I know it's not the best! I'll work on it...

2022-02-24 17:40 UTC, mcharrod commented on app/controllers/admin/merchants_controller.rb
> +      param_hash[:name] = params[:name] unless params[:name] == "" || params[:name] == nil
Hey Mark, I like that you are trying to guard against blank names. Luckily, our model validations does that for us. It looks like when trying to use this functionality in local host, some things slip by. Have a look at the merchant items controller, and give that a go instead. Let me know if you have questions!

2022-02-24 17:43 UTC, mcharrod requested changes
Hey Mark, I've added some comments for some changes that should be made before merging into developer. Looks like with our current set up when we type in a blank name, it redirects without making any changes. Ideally, we should get a flash notification that gives us an error, something our model validations will take care of for us. Have a look at the merchant items controller to see this in action!

2022-02-25 00:54 UTC, jwgalvin commented
Pulled down and passes tests.  Nice work implementing the changes requested.  Merging to main.

2022-02-25 00:54 UTC, merged