Us24 total rev
mcharrod/little-esty-shop pull request #85
Opened 2022-02-23 23:59 UTC by jwgalvin

Total Revenue added to the bottom of merchant invoice

2022-02-24 17:27 UTC, mcharrod commented on app/views/merchants/invoices/show.html.erb
> +    <h3> Total amount from <%="#{@invoice.customer.first_name}"%>'s invoice: $<%= "#{@items.sum(:unit_price)}"%>
Good job with this!! A refactor you could do is to make the .sum(:unit_price) a model method for the invoice, then call @invoice.total_rev or something instead of creating an items var.

2022-02-24 17:30 UTC, mcharrod commented on spec/features/merchants/invoices/show_spec.rb
> +    expect(page).to have_content("Total amount from Marky's invoice: $125")
Joe I would like it if you created a model method to test that our revenue method is working properly -- that is where you would put the number 125 verbatim. It would be better in our feature test to call the method we create in the model for this like ("total amount from Marky's invoice: #{@invoice.total_rev}") instead. The functionality looks good -- after some refactors it will be ready for merging!

2022-02-24 17:31 UTC, mcharrod requested changes
Hey Joe, the functionality for this feature looks good -- I would just ask that we make some slight changes to avoid calling the number verbatim in our feature test

2022-02-25 02:10 UTC, jwgalvin commented
Added the method to model and a model test.  confirmed all tests passed.

2022-02-25 02:36 UTC, mcharrod approved these changes
Looks good! Only other piece of feedback -- in our model test, I wish that you added more items to see if the sum is working rather than grabbing one number :)

2022-02-25 03:14 UTC, mcharrod commented
Thank you for updating that, Joe! I've gone ahead and merged it into developer, all passing specs

2022-02-25 03:14 UTC, merged